import type { ExperimentLogEntry, NextStepContent, TradeoffRow } from '@/lib/editorial-content';

export const configurarContent = {
  tradeoffs: [
    { option: 'Tamanho da validação', whatItIs: 'Parte dos dados separada para estimar como uma escolha se comporta fora do treino.', worksWellWhen: 'A equipe explicita o que perde em dados de treino e o que ganha em uma estimativa menos instável.', canBeProblematicWhen: 'A validação é tratada como resposta final ou a comparação muda de divisão entre rodadas.', observe: 'Tamanho do treino, variação dos resultados e comparabilidade entre testes.', neutralExample: 'Separar parte de registros fictícios de empréstimos de biblioteca para conferir uma hipótese.' },
    { option: 'Estratificação (`stratify=y`)', whatItIs: 'Mantém aproximadamente a proporção das classes nas partes separadas.', worksWellWhen: 'Há classes desbalanceadas e cada parte precisa representar melhor o conjunto original.', canBeProblematicWhen: 'É usada sem verificar se cada classe tem casos suficientes ou quando há outra estrutura relevante no dado.', observe: 'Contagem e proporção de cada classe em treino e validação.', neutralExample: 'Preservar a proporção de categorias em uma pesquisa escolar simulada.' },
    { option: 'Profundidade da árvore', whatItIs: 'Limite de níveis que uma árvore de decisão pode criar. Aplica-se a árvores e, conforme a implementação, às árvores de uma floresta.', worksWellWhen: 'A complexidade é comparada como uma hipótese sobre padrões simples ou detalhados.', canBeProblematicWhen: 'Uma árvore memoriza particularidades do treino ou é simplificada demais para captar padrões.', observe: 'Diferença entre treino e validação, além de erros recorrentes.', neutralExample: 'Uma árvore que separa espécies fictícias por medidas de folhas.' },
    { option: 'Número de árvores (`n_arvores`)', whatItIs: 'Quantidade de árvores combinadas em uma floresta aleatória. Não se aplica a árvore única, regressão logística, SVM ou Naive Bayes.', worksWellWhen: 'A equipe observa estabilidade e custo como parte da comparação.', canBeProblematicWhen: 'Mais processamento é assumido como melhoria automática ou a mudança é confundida com outro seletor.', observe: 'Tempo, uso de recursos e variação da avaliação com o restante fixo.', neutralExample: 'Conjunto de árvores em dados sintéticos de hábitos de leitura.' },
    { option: 'Mínimo por folha (`min_samples_leaf`)', whatItIs: 'Quantidade mínima de exemplos que uma folha de árvore precisa conter. Aplica-se a árvores e florestas.', worksWellWhen: 'A equipe quer limitar regras formadas por poucos casos.', canBeProblematicWhen: 'O limite impede padrões que precisariam de mais detalhe ou é alterado junto com profundidade.', observe: 'Tamanho das folhas, diferença treino–validação e estabilidade dos erros.', neutralExample: 'Evitar uma regra baseada em um único registro de jardim fictício.' },
    { option: 'Pesos de classe (`class_weight`)', whatItIs: 'Forma de atribuir importância diferente a erros de classes no treinamento; só funciona nos modelos que expõem esse parâmetro.', worksWellWhen: 'O desbalanceamento e o tipo de erro merecem ser discutidos antes do teste.', canBeProblematicWhen: 'É usado para “consertar” dados sem ler as métricas por classe ou não é suportado pelo modelo.', observe: 'Precisão, revocação e matriz de confusão por classe; confirmação na referência técnica.', neutralExample: 'Comparar erros em categorias raras de pedidos fictícios.' },
    { option: 'Padronização', whatItIs: 'Transforma escalas numéricas para que medidas com unidades diferentes não dominem pela magnitude. Use em um pipeline ajustado só no treino.', worksWellWhen: 'O modelo é sensível à escala, como regressão logística e SVM; árvores em geral não dependem da escala da mesma forma.', canBeProblematicWhen: 'O transformador é ajustado com validação/teste, causando vazamento, ou espera-se efeito em árvore por uma razão errada.', observe: 'Ordem do pipeline, escalas das características e comparação com os demais passos fixos.', neutralExample: 'Combinar centímetros e minutos em registros fictícios de atividades.' },
    { option: 'Conjunto de descritores', whatItIs: 'Seleção de sinais visuais usados pelo modelo, como medidas de cor, brilho ou textura. Aplica-se à trilha de Visão.', worksWellWhen: 'A seleção testa uma hipótese sobre informação útil e redundância.', canBeProblematicWhen: 'Um conjunto é removido sem inspecionar imagens, ou a seleção é feita olhando a validação repetidamente.', observe: 'Mudança nos erros, cobertura dos casos e coerência com a galeria qualitativa.', neutralExample: 'Comparar descritores de folhas inventadas sob iluminação variada.' },
    { option: 'Força `C` e `gamma`', whatItIs: '`C` controla o compromisso de regularização em modelos lineares e SVM; `gamma` define o alcance de influência no SVM com kernel RBF. `gamma` não se aplica a SVM linear, regressão logística ou Naive Bayes.', worksWellWhen: 'A aplicabilidade ao modelo é confirmada e as escolhas são testadas com os demais fatores controlados.', canBeProblematicWhen: 'Os valores são interpretados isoladamente, especialmente no RBF, ou se atribui efeito a um parâmetro ignorado pelo modelo.', observe: 'Tipo de SVM, diferença treino–validação, estabilidade e custo.', neutralExample: 'Fronteiras entre grupos artificiais desenhados em um plano.' },
    { option: 'Limite de vocabulário (`max_palavras`)', whatItIs: 'Quantidade máxima de termos mantidos na representação de texto. Aplica-se à trilha de Linguagem Natural.', worksWellWhen: 'A equipe compara cobertura de vocabulário, ruído, memória e tempo.', canBeProblematicWhen: 'Um vocabulário grande é tomado como melhor sem observar termos raros ou custo.', observe: 'Dimensão da matriz, tempo e exemplos de termos mantidos ou excluídos.', neutralExample: 'Comentários inventados sobre eventos de uma escola.' },
    { option: 'Frequência mínima (`min_df`)', whatItIs: 'Número mínimo de documentos em que um termo precisa aparecer para entrar no vocabulário. Aplica-se à representação textual.', worksWellWhen: 'A equipe quer examinar o equilíbrio entre filtrar ruído e manter sinais raros.', canBeProblematicWhen: 'Termos pouco frequentes são descartados sem revisar se carregam contexto importante.', observe: 'Vocabulário resultante, termos removidos e erros por classe.', neutralExample: 'Bilhetes fictícios de clubes estudantis.' },
    { option: 'N-gramas', whatItIs: 'Sequências de uma, duas ou mais palavras que preservam contexto local. Aplica-se à representação textual.', worksWellWhen: 'Expressões curtas podem importar e há recursos para uma matriz mais ampla.', canBeProblematicWhen: 'A dimensionalidade e a raridade crescem sem evidência de ganho interpretável.', observe: 'Tamanho do vocabulário, memória, tempo e exemplos de sequências geradas.', neutralExample: 'Frases inventadas de avaliações de filmes.' },
  ] satisfies TradeoffRow[],
  plan: [{ hypothesis: 'Escrevam uma relação que pode ser contrariada pela evidência.', alteration: 'Mudem uma escolha aplicável ao modelo; mantenham as demais registradas.', result: 'Reservem este campo para a medida e os erros observados depois da execução.', matrixFinding: 'Anotem qual padrão de acerto ou confusão merece atenção.', nextTest: 'Definam antes qual evidência sustenta manter ou descartar a hipótese.' }] satisfies ExperimentLogEntry[],
  nextStep: { href: '/modelar', label: 'Próxima etapa', title: 'Leia o notebook antes de alterar', description: 'Com um plano registrado, compreendam a célula e a referência técnica que executam o experimento.' } satisfies NextStepContent,
};
