import type { NextStepContent, Question, TradeoffRow } from '@/lib/editorial-content';

export const modelarContent = {
  modelTradeoffs: [
    { option: 'Regressão logística', whatItIs: 'Modelo linear que combina características para estimar a tendência de cada classe.', worksWellWhen: 'Sinais podem ser organizados aproximadamente por uma fronteira linear; é comum em dados numéricos padronizados e texto vetorizado.', canBeProblematicWhen: 'A relação exige uma fronteira muito irregular ou as escalas não foram tratadas quando isso importa.', observe: 'Desempenho por classe, diferença treino–validação e, com cuidado, os coeficientes como associação.', neutralExample: 'Classificar comentários fictícios de uma biblioteca a partir de palavras representadas em números.' },
    { option: 'Árvore de decisão', whatItIs: 'Modelo que cria perguntas sequenciais sobre características para separar casos.', worksWellWhen: 'Há relações por faixas, condições ou interações que uma regra em árvore pode representar.', canBeProblematicWhen: 'Cria regras muito específicas para o treino ou fica simples demais para distinguir padrões relevantes.', observe: 'Diferença entre treino e validação, tamanho das regras e tipos de erro.', neutralExample: 'Separar plantas inventadas por medidas de folhas e categorias de solo.' },
    { option: 'Floresta aleatória', whatItIs: 'Conjunto de árvores que combina várias previsões para reduzir a dependência de uma única árvore.', worksWellWhen: 'Há padrões variados em dados tabulares e a equipe pode considerar custo e estabilidade.', canBeProblematicWhen: 'O custo de treino e leitura aumenta, ou a média das árvores é tratada como explicação causal.', observe: 'Tempo, uso de recursos, desempenho por classe e consistência entre rodadas.', neutralExample: 'Classificar registros sintéticos de empréstimos de equipamentos escolares.' },
    { option: 'SVM linear', whatItIs: 'SVM com uma fronteira linear; busca separar classes com uma margem entre elas.', worksWellWhen: 'Há muitas características, como em representações de texto, e uma separação linear é uma hipótese razoável.', canBeProblematicWhen: 'A estrutura pede uma fronteira não linear ou a escala das características é ignorada quando ela é relevante.', observe: 'Confirmem que a implementação e a fronteira são lineares; observem escala quando aplicável, erros por classe e custo.', neutralExample: 'Distinguir mensagens fictícias por uma representação de termos.' },
    { option: 'SVM com kernel RBF', whatItIs: 'SVM que pode representar fronteiras não lineares usando uma noção de proximidade entre casos.', worksWellWhen: 'Há uma hipótese de padrões curvos ou locais e as características estão em escalas comparáveis.', canBeProblematicWhen: 'Custo e sensibilidade às escolhas tornam a leitura difícil, especialmente sem padronização.', observe: 'Que o kernel é RBF, a interação entre as escolhas expostas, treino versus validação e tempo.', neutralExample: 'Separar grupos artificiais desenhados em regiões curvas de um plano.' },
    { option: 'Naive Bayes Multinomial', whatItIs: 'Modelo probabilístico frequentemente usado com contagens ou representações não negativas de texto.', worksWellWhen: 'A representação é compatível com esse tipo de entrada e a equipe quer comparar uma hipótese probabilística simples.', canBeProblematicWhen: 'Características negativas ou inadequadas são usadas, ou a independência aproximada entre termos é tomada como fato.', observe: 'Compatibilidade da representação, métricas por classe e termos associados apenas como pistas.', neutralExample: 'Organizar bilhetes fictícios de clubes por palavras presentes.' },
  ] satisfies TradeoffRow[],
  questions: [
    { id: 'cell-purpose', question: 'O que esta célula recebe, transforma ou produz antes de vocês mudarem algo?', hint: 'Leiam o texto, os nomes das variáveis e a saída juntos.' },
    { id: 'interface', question: 'Qual classe e quais argumentos a referência técnica diz que são aceitos?', hint: 'Confirmem o nome exato e os valores padrão, sem copiar uma configuração de outro caso.' },
    { id: 'applicable-choice', question: 'A opção escolhida realmente é usada por este modelo e nesta etapa?', hint: 'Um seletor que não se aplica não explica um resultado.' },
    { id: 'reproducible-run', question: 'O que a equipe precisa registrar para conseguir refazer esta rodada?', hint: 'Anotem divisão, escolhas, versão do notebook e o que foi executado.' },
  ] satisfies Question[],
  nextStep: { href: '/avaliar', label: 'Próxima etapa', title: 'Transforme a saída em evidência', description: 'Leiam métricas, matriz de confusão e exemplos de erro antes de decidir qual pergunta investigar depois.' } satisfies NextStepContent,
};
