import { Callout } from '@/components/editorial/callout';
import { ExperimentLog } from '@/components/editorial/experiment-log';
import { PageHeader } from '@/components/editorial/page-header';
import { PageContents } from '@/components/editorial/page-contents';
import { PhaseNavigation } from '@/components/editorial/phase-navigation';
import { QuestionList } from '@/components/editorial/question-list';
import { TradeoffTable } from '@/components/editorial/tradeoff-table';
import { avaliarContent } from '@/lib/avaliar-content';
import { findHandbookPage } from '@/lib/handbook-pages';

const page = findHandbookPage(['avaliar'])!;
const matrix = [['Classe real \\ prevista', 'Azul', 'Verde', 'Laranja'], ['Azul', '12', '2', '1'], ['Verde', '3', '10', '2'], ['Laranja', '1', '2', '11']];

export function AvaliarPage() {
  return <article className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20 lg:px-12 lg:py-24">
    <PageHeader {...page} />
    <PageContents items={[{ href: '#metricas', label: 'Métricas' }, { href: '#matriz', label: 'Matriz de confusão' }, { href: '#leitura', label: 'Leitura dos resultados' }, { href: '#diagnosticos', label: 'Diagnósticos' }, { href: '#perguntas', label: 'Perguntas e diário' }]} />
    <section className="mt-12" aria-labelledby="metricas"><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Ler mais de um número</p><h2 id="metricas" className="mt-3 text-3xl font-semibold tracking-tight">Cada métrica responde a uma pergunta diferente</h2><p className="mt-4 max-w-3xl leading-7 text-muted-foreground">Acurácia resume acertos totais. Precisão pergunta se as previsões de uma classe estavam certas; revocação pergunta se os casos reais dessa classe foram encontrados. F1 equilibra as duas para uma classe, e F1-macro dá o mesmo peso ao F1 de cada classe. Leiam sempre junto das contagens e dos erros.</p><div className="mt-7"><TradeoffTable rows={avaliarContent.metricTradeoffs} caption="Perguntas que métricas de classificação ajudam — e não ajudam — a responder." /></div></section>
    <section className="mt-16" aria-labelledby="matriz"><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Exemplo inventado</p><h2 id="matriz" className="mt-3 text-3xl font-semibold tracking-tight">Matriz de confusão: onde os erros vão parar</h2><p className="mt-4 max-w-3xl leading-7 text-muted-foreground">Esta matriz usa três classes e números totalmente fictícios. Linhas são as classes reais; colunas, as previstas. A diagonal mostra acertos. Toda célula fora dela descreve uma direção específica de confusão.</p>{/* oxlint-disable-next-line jsx-a11y/no-noninteractive-tabindex -- região rolável precisa receber foco para rolagem pelo teclado. */}<div tabIndex={0} className="mt-6 max-w-2xl overflow-x-auto rounded-2xl border border-border focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary" aria-label="Matriz de confusão fictícia; deslize horizontalmente para ver todas as colunas"><table className="w-full min-w-[520px] text-center"><caption className="caption-top px-5 py-4 text-left font-semibold">Exemplo didático — não representa dados ou resultados da OIAA.</caption><thead className="bg-[#031721] text-white"><tr>{matrix[0].map((cell) => <th key={cell} scope="col" className="px-4 py-3">{cell}</th>)}</tr></thead><tbody>{matrix.slice(1).map((row, rowIndex) => <tr key={row[0]} className="border-t border-border">{row.map((cell, colIndex) => colIndex === 0 ? <th key={cell} scope="row" className="bg-muted px-4 py-4 text-left">{cell}</th> : <td key={cell} className={`px-4 py-4 font-semibold ${rowIndex + 1 === colIndex ? 'bg-primary/25 text-foreground' : 'bg-accent/15 text-foreground'}`}>{cell}</td>)}</tr>)}</tbody></table></div><div className="mt-5 grid gap-4 md:grid-cols-3"><article className="rounded-xl bg-muted p-4"><h3 className="font-semibold">Linha</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">Comece pela classe real para saber como seus casos foram distribuídos.</p></article><article className="rounded-xl bg-muted p-4"><h3 className="font-semibold">Coluna</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">Leia uma previsão para ver de quais classes reais ela veio.</p></article><article className="rounded-xl bg-muted p-4"><h3 className="font-semibold">Fora da diagonal</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">Cada número é um erro a investigar com contexto, não uma conclusão automática.</p></article></div></section>
    <section className="mt-12 grid gap-5 lg:grid-cols-2" id="leitura"><Callout kind="conceito" title="Falso positivo e falso negativo">Para uma classe escolhida, falso positivo é prever essa classe quando o caso real era outro. Falso negativo é deixar de prevê-la quando ela era real. A direção importa: a mesma quantidade de erros pode ter efeitos diferentes.</Callout><Callout kind="atencao" title="Classe crítica e custo assimétrico">Uma equipe precisa discutir qual classe ou direção de erro exige mais cuidado no contexto imaginado. Não existe prioridade automática: comparem consequências, pessoas afetadas e evidências antes de interpretar a métrica.</Callout></section>
    <section className="mt-16 grid gap-5 lg:grid-cols-2"><Callout kind="dica" title="Leia o `classification_report` classe por classe">Localizem precisão, revocação, F1 e suporte de cada classe. O suporte é a quantidade de casos reais daquela classe; ele ajuda a dar contexto a uma métrica. Depois confirmem a história na matriz de confusão.</Callout><Callout kind="dica" title="Compare treino e validação">Quando o treino parece muito melhor que a validação, investiguem possível sobreajuste. Quando o desempenho é baixo nos dois, investiguem possível subajuste. São sinais para examinar junto do tamanho das amostras, dos erros e do plano de experimento — não conclusões automáticas.</Callout></section>
    <section className="mt-16" aria-labelledby="diagnosticos"><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Diagnósticos por trilha</p><h2 id="diagnosticos" className="mt-3 text-3xl font-semibold tracking-tight">Volte aos casos, não apenas ao resumo</h2><div className="mt-6 grid gap-4 lg:grid-cols-3"><article className="rounded-2xl border border-border bg-card p-5"><h3 className="text-xl font-semibold">Tabular</h3><p className="mt-2 leading-7 text-muted-foreground">Importância de características e magnitude de coeficientes podem sugerir associações usadas pelo modelo. Não provam causa, justiça ou utilidade fora dos dados observados.</p></article><article className="rounded-2xl border border-border bg-card p-5"><h3 className="text-xl font-semibold">Visão</h3><p className="mt-2 leading-7 text-muted-foreground">Leiam uma galeria qualitativa de imagens incorretas. Procurem condições recorrentes de captura, enquadramento, iluminação ou textura antes de atribuir uma explicação.</p></article><article className="rounded-2xl border border-border bg-card p-5"><h3 className="text-xl font-semibold">Linguagem natural</h3><p className="mt-2 leading-7 text-muted-foreground">Observem precisão e revocação da classe que a equipe considera crítica e leiam termos com maior peso como pistas de associação, sempre conferindo contexto e exemplos.</p></article></div></section>
    <div className="mt-16" id="perguntas"><QuestionList questions={avaliarContent.questions} /></div><div className="mt-8"><ExperimentLog entries={avaliarContent.journal} title="Diário · resultado, leitura e próximo teste" /></div><PhaseNavigation current="/avaliar" />
  </article>;
}
