import { Callout } from '@/components/editorial/callout';
import { PageHeader } from '@/components/editorial/page-header';
import { PageContents } from '@/components/editorial/page-contents';
import { PhaseNavigation } from '@/components/editorial/phase-navigation';
import { QuestionList } from '@/components/editorial/question-list';
import { TradeoffTable } from '@/components/editorial/tradeoff-table';
import { findHandbookPage } from '@/lib/handbook-pages';
import { modelarContent } from '@/lib/modelar-content';

const page = findHandbookPage(['modelar'])!;

export function ModelarPage() {
  return <article className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20 lg:px-12 lg:py-24">
    <PageHeader {...page} />
    <PageContents items={[{ href: '#anatomia', label: 'Anatomia do notebook' }, { href: '#interface', label: 'Interface' }, { href: '#modelos', label: 'Modelos' }, { href: '#perguntas', label: 'Perguntas' }]} />
    <section className="mt-12" aria-labelledby="anatomia"><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Anatomia do notebook</p><h2 id="anatomia" className="mt-3 text-3xl font-semibold tracking-tight">Leia na ordem em que o experimento acontece</h2><div className="mt-6 grid gap-4 lg:grid-cols-4"><article className="rounded-2xl border border-border bg-card p-5"><h3 className="font-semibold">1. Texto</h3><p className="mt-2 leading-7 text-muted-foreground">Explica o objetivo, a pergunta ou uma instrução. Leia antes de executar.</p></article><article className="rounded-2xl border border-border bg-card p-5"><h3 className="font-semibold">2. Código</h3><p className="mt-2 leading-7 text-muted-foreground">Cria dados, transforma informações ou ajusta um modelo. Nomes indicam entradas e saídas.</p></article><article className="rounded-2xl border border-border bg-card p-5"><h3 className="font-semibold">3. Execução</h3><p className="mt-2 leading-7 text-muted-foreground">Células dependem das anteriores. Executar fora de ordem pode usar algo que ainda não existe.</p></article><article className="rounded-2xl border border-border bg-card p-5"><h3 className="font-semibold">4. Saída</h3><p className="mt-2 leading-7 text-muted-foreground">É evidência: mensagem, tabela, gráfico ou erro que pede leitura — não um veredito isolado.</p></article></div></section>
    <section className="mt-12 grid gap-5 lg:grid-cols-2"><Callout kind="dica" title="Quando aparecer um erro">Localizem a célula indicada, releiam a mensagem inteira, confiram se as células anteriores foram executadas e corrijam somente o que entenderam. Depois, reexecutem a partir do ponto necessário e observem a nova saída.</Callout><Callout kind="atencao" title="Não pule para a última célula">Uma execução anterior pode preparar dados, importar uma classe ou definir uma variável. Pular etapas pode produzir erro, usar estado antigo ou esconder a causa de uma diferença.</Callout></section>
    <section className="mt-16" aria-labelledby="interface"><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Ler a interface</p><h2 id="interface" className="mt-3 text-3xl font-semibold tracking-tight">`fit`, `predict` e argumentos nomeados</h2><div className="mt-5 max-w-3xl space-y-4 leading-7 text-muted-foreground"><p>Na interface do scikit-learn, `fit` ajusta um objeto usando os exemplos de treino e seus rótulos quando a tarefa precisa deles. `predict` usa o objeto já ajustado para produzir previsões de novos casos compatíveis.</p><p>Argumentos nomeados tornam explícito o papel de uma escolha, como quando uma chamada informa o nome de um parâmetro e seu valor. A referência técnica diz quais nomes a classe aceita, o que significam, seus valores padrão e se se aplicam ao modelo escolhido.</p><p>Nos notebooks, uma estrutura `if` / `elif` / `else` pode escolher qual classe de modelo será construída conforme a opção selecionada. Leiam cada condição para descobrir qual caminho será executado; não preencham lacunas por semelhança com outro caminho.</p></div></section>
    <section className="mt-16 grid gap-5 lg:grid-cols-2"><Callout kind="conceito" title="Pipeline evita que informação atravesse a fronteira">Um pipeline organiza transformações e modelo em sequência. `fit_transform` aprende uma transformação no treino e a aplica nele; depois, `transform` reaplica somente o que foi aprendido aos dados separados. Assim, validação e teste não ajudam a definir a transformação.</Callout><Callout kind="dica" title="Reproduzir não é otimizar">`random_state=42` costuma fixar a fonte de aleatoriedade para que uma divisão ou rodada possa ser refeita. Registrem-no para comparar de modo justo; ele não é um hiperparâmetro a ser procurado como se escondesse uma resposta.</Callout></section>
    <section className="mt-16" aria-labelledby="modelos"><p className="text-sm font-bold uppercase tracking-[.14em] text-primary">Famílias de modelo</p><h2 id="modelos" className="mt-3 text-3xl font-semibold tracking-tight">Compare hipóteses, limites e evidências</h2><p className="mt-4 max-w-3xl leading-7 text-muted-foreground">Uma família descreve como o modelo representa padrões, não uma escolha vencedora. Confirmem a representação de entrada e os argumentos disponíveis no notebook antes de qualquer comparação.</p><div className="mt-7"><TradeoffTable rows={modelarContent.modelTradeoffs} caption="Trade-offs de famílias de modelos citadas nas trilhas, sem recomendação para um desafio." /></div></section>
    <section className="mt-16 grid gap-5 lg:grid-cols-2"><Callout kind="dica" title="Como ler uma referência técnica">Procurem o nome exato da classe, a assinatura e os parâmetros. Leiam o significado, o valor padrão e o efeito esperado de uma mudança. Depois confirmem se o notebook usa a mesma versão e se a opção aparece naquele caminho.</Callout><Callout kind="regra" title="O que não fazer">Não preencham lacunas sem compreensão, não pulem células, não ajustem escolhas usando dados de teste e não copiem código de terceiros como se fosse da equipe. Registrem dúvidas e peçam explicação conceitual quando necessário.</Callout></section>
    <div className="mt-16" id="perguntas"><QuestionList questions={modelarContent.questions} /></div><PhaseNavigation current="/modelar" />
  </article>;
}
